name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r adapters/legacy_csv/requirements.txt -r api/requirements.txt
      - run: |
          black --check adapters api scripts || (echo "Run black ." && exit 1)
          isort --check-only adapters api scripts
      - run: |
          python - <<'PY'
          import pathlib
          ttl = pathlib.Path("core/ontology.ttl").read_text()
          assert "AllowedUnit" in ttl
          print("Ontology sanity OK")
          PY
      - env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USER: ${{ secrets.NEO4J_USER }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        run: |
          if [ -n "$NEO4J_URI" ]; then
            python scripts/load_to_neo4j.py scripts/demo.cypher
          else
            echo "No Neo4j secrets; skipping demo load."
          fi
